import type { Database } from "./supabase";

export type { Database };

/**
 * Convenience aliases for the most-used Supabase table types.
 * Source: src/types/supabase.ts (auto-generated by `supabase gen types`).
 */
export type Tables = Database["public"]["Tables"];
export type Profile = Tables["profiles"]["Row"];
export type Organization = Tables["organizations"]["Row"];
export type OrganizationMember = Tables["organization_members"]["Row"];

export type OrganizationRole = Database["public"]["Enums"]["organization_role"];

/**
 * Composite type the app uses everywhere a "current user" is needed.
 * Combines the Supabase auth identity with the joined profile and the joined
 * organization membership (both may be null for users still in onboarding).
 */
export type CurrentUser = {
  id: string;
  email: string;
  profile: Pick<Profile, "id" | "full_name" | "avatar_url"> | null;
  membership: Pick<OrganizationMember, "organization_id" | "role"> | null;
};

/**
 * CurrentUser narrowed to having an organization membership (post-onboarding).
 * Returned by `requireOrg()` and `requireRole()`.
 */
export type CurrentUserWithMembership = CurrentUser & {
  membership: NonNullable<CurrentUser["membership"]>;
};
